import { Issue } from '../entities/Issue';
import { IssueRepository } from './adapter-interfaces/IssueRepository';
import { Project } from '../entities/Project';
import { StoryObjectMap } from '../entities/StoryObjectMap';
import { ProjectRepository } from './adapter-interfaces/ProjectRepository';
import { Member } from '../entities/Member';
import { DateRepository } from './adapter-interfaces/DateRepository';
import { SpreadsheetRepository } from './adapter-interfaces/SpreadsheetRepository';
import { ActionAnnouncementUseCase } from './ActionAnnouncementUseCase';
import { SetWorkflowManagementIssueToStoryUseCase } from './SetWorkflowManagementIssueToStoryUseCase';
import { ClearPastNextActionDateHourUseCase } from './ClearPastNextActionDateHourUseCase';
import { AnalyzeProblemByIssueUseCase } from './AnalyzeProblemByIssueUseCase';
import { AnalyzeStoriesUseCase } from './AnalyzeStoriesUseCase';
import { ClearDependedIssueURLUseCase } from './ClearDependedIssueURLUseCase';
import { SetDependedIssueUrlForOpenTaskPRsUseCase } from './SetDependedIssueUrlForOpenTaskPRsUseCase';
import { StaleTaskPullRequestCloseUseCase } from './StaleTaskPullRequestCloseUseCase';
import { CreateEstimationIssueUseCase } from './CreateEstimationIssueUseCase';
import { ConvertCheckboxToIssueInStoryIssueUseCase } from './ConvertCheckboxToIssueInStoryIssueUseCase';
import { ChangeStatusByStoryColorUseCase } from './ChangeStatusByStoryColorUseCase';
import { SetNoStoryIssueToStoryUseCase } from './SetNoStoryIssueToStoryUseCase';
import { CreateNewStoryByLabelUseCase } from './CreateNewStoryByLabelUseCase';
import { AssignNoAssigneeIssueToManagerUseCase } from './AssignNoAssigneeIssueToManagerUseCase';
import { UpdateIssueStatusByLabelUseCase } from './UpdateIssueStatusByLabelUseCase';
import { IssueNoStatusUpdateUseCase } from './IssueNoStatusUpdateUseCase';
import { RotationOrderEntry, StartPreparationUseCase } from './StartPreparationUseCase';
import { AgentDesignationLabelAdoptUseCase } from './AgentDesignationLabelAdoptUseCase';
import { RevertOrphanedPreparationUseCase } from './RevertOrphanedPreparationUseCase';
import { RevertNotReadyReviewQueueIssueUseCase } from './RevertNotReadyReviewQueueIssueUseCase';
import { TriagerApprovalDispatchUseCase } from './TriagerApprovalDispatchUseCase';
import { ProjectRequiredFieldCreateUseCase } from './ProjectRequiredFieldCreateUseCase';
import { SetupTowerDefenceProjectUseCase } from './SetupTowerDefenceProjectUseCase';
import { UpdateRateLimitCacheUseCase } from './UpdateRateLimitCacheUseCase';
import { DailySecurityScanConfig, DailySecurityScanUseCase } from './DailySecurityScanUseCase';
import { QualityCheckAdvanceUseCase } from './QualityCheckAdvanceUseCase';
import { ReopenedDoneIssueRevertUseCase } from './ReopenedDoneIssueRevertUseCase';
export declare class ProjectNotFoundError extends Error {
    constructor(message: string);
}
export declare class HandleScheduledEventUseCase {
    readonly projectRequiredFieldCreateUseCase: ProjectRequiredFieldCreateUseCase;
    readonly setupTowerDefenceProjectUseCase: SetupTowerDefenceProjectUseCase;
    readonly actionAnnouncementUseCase: ActionAnnouncementUseCase;
    readonly setWorkflowManagementIssueToStoryUseCase: SetWorkflowManagementIssueToStoryUseCase;
    readonly clearPastNextActionUseCase: ClearPastNextActionDateHourUseCase;
    readonly analyzeProblemByIssueUseCase: AnalyzeProblemByIssueUseCase;
    readonly analyzeStoriesUseCase: AnalyzeStoriesUseCase;
    readonly clearDependedIssueURLUseCase: ClearDependedIssueURLUseCase;
    readonly setDependedIssueUrlForOpenTaskPRsUseCase: SetDependedIssueUrlForOpenTaskPRsUseCase;
    readonly staleTaskPullRequestCloseUseCase: StaleTaskPullRequestCloseUseCase;
    readonly createEstimationIssueUseCase: CreateEstimationIssueUseCase;
    readonly convertCheckboxToIssueInStoryIssueUseCase: ConvertCheckboxToIssueInStoryIssueUseCase;
    readonly changeStatusByStoryColorUseCase: ChangeStatusByStoryColorUseCase;
    readonly setNoStoryIssueToStoryUseCase: SetNoStoryIssueToStoryUseCase;
    readonly createNewStoryByLabelUseCase: CreateNewStoryByLabelUseCase;
    readonly assignNoAssigneeIssueToManagerUseCase: AssignNoAssigneeIssueToManagerUseCase;
    readonly updateIssueStatusByLabelUseCase: UpdateIssueStatusByLabelUseCase;
    readonly issueNoStatusUpdateUseCase: IssueNoStatusUpdateUseCase;
    readonly startPreparationUseCase: StartPreparationUseCase;
    readonly revertOrphanedPreparationUseCase: RevertOrphanedPreparationUseCase;
    readonly revertNotReadyReviewQueueIssueUseCase: RevertNotReadyReviewQueueIssueUseCase;
    readonly triagerApprovalDispatchUseCase: TriagerApprovalDispatchUseCase;
    readonly agentDesignationLabelAdoptUseCase: AgentDesignationLabelAdoptUseCase;
    readonly updateRateLimitCacheUseCase: UpdateRateLimitCacheUseCase | null;
    readonly dailySecurityScanUseCase: DailySecurityScanUseCase | null;
    readonly qualityCheckAdvanceUseCase: QualityCheckAdvanceUseCase;
    readonly reopenedDoneIssueRevertUseCase: ReopenedDoneIssueRevertUseCase;
    readonly dateRepository: DateRepository;
    readonly spreadsheetRepository: SpreadsheetRepository;
    readonly projectRepository: ProjectRepository;
    readonly issueRepository: IssueRepository;
    constructor(projectRequiredFieldCreateUseCase: ProjectRequiredFieldCreateUseCase, setupTowerDefenceProjectUseCase: SetupTowerDefenceProjectUseCase, actionAnnouncementUseCase: ActionAnnouncementUseCase, setWorkflowManagementIssueToStoryUseCase: SetWorkflowManagementIssueToStoryUseCase, clearPastNextActionUseCase: ClearPastNextActionDateHourUseCase, analyzeProblemByIssueUseCase: AnalyzeProblemByIssueUseCase, analyzeStoriesUseCase: AnalyzeStoriesUseCase, clearDependedIssueURLUseCase: ClearDependedIssueURLUseCase, setDependedIssueUrlForOpenTaskPRsUseCase: SetDependedIssueUrlForOpenTaskPRsUseCase, staleTaskPullRequestCloseUseCase: StaleTaskPullRequestCloseUseCase, createEstimationIssueUseCase: CreateEstimationIssueUseCase, convertCheckboxToIssueInStoryIssueUseCase: ConvertCheckboxToIssueInStoryIssueUseCase, changeStatusByStoryColorUseCase: ChangeStatusByStoryColorUseCase, setNoStoryIssueToStoryUseCase: SetNoStoryIssueToStoryUseCase, createNewStoryByLabelUseCase: CreateNewStoryByLabelUseCase, assignNoAssigneeIssueToManagerUseCase: AssignNoAssigneeIssueToManagerUseCase, updateIssueStatusByLabelUseCase: UpdateIssueStatusByLabelUseCase, issueNoStatusUpdateUseCase: IssueNoStatusUpdateUseCase, startPreparationUseCase: StartPreparationUseCase, revertOrphanedPreparationUseCase: RevertOrphanedPreparationUseCase, revertNotReadyReviewQueueIssueUseCase: RevertNotReadyReviewQueueIssueUseCase, triagerApprovalDispatchUseCase: TriagerApprovalDispatchUseCase, agentDesignationLabelAdoptUseCase: AgentDesignationLabelAdoptUseCase, updateRateLimitCacheUseCase: UpdateRateLimitCacheUseCase | null, dailySecurityScanUseCase: DailySecurityScanUseCase | null, qualityCheckAdvanceUseCase: QualityCheckAdvanceUseCase, reopenedDoneIssueRevertUseCase: ReopenedDoneIssueRevertUseCase, dateRepository: DateRepository, spreadsheetRepository: SpreadsheetRepository, projectRepository: ProjectRepository, issueRepository: IssueRepository);
    run: (input: {
        projectName: string;
        org: string;
        projectUrl: string;
        manager: Member["name"];
        workingReport: {
            repo: string;
            members: Member["name"][];
            spreadsheetUrl: string;
        };
        urlOfStoryView: string;
        disabled: boolean;
        labelsAsLlmAgentName?: string[] | null;
        labelsNotRequiringPullRequest?: string[] | null;
        changeTargetPathAliases?: Record<string, string> | null;
        allowedIssueAuthors?: string[] | null;
        autoAssignManagerAuthors?: string[] | null;
        agents?: string[] | null;
        startPreparation?: {
            defaultAgentName: string;
            defaultLlmModelName?: string | null;
            fallbackLlmModelName?: string | null;
            defaultLlmAgentName?: string | null;
            configFilePath: string;
            maximumPreparingIssuesCount: number | null;
            utilizationPercentageThreshold?: number;
            allowedIssueAuthors?: string[] | null;
            preparationProcessCheckCommand?: string;
            codexHomeCandidates?: string[] | null;
            awLogDirectoryPath?: string;
            awLogStaleThresholdMinutes?: number;
            awaitingQualityCheckStatus?: string | null;
            autoAdvanceQualityCheckEnabled?: boolean;
            autoRevertReopenedDoneEnabled?: boolean;
            labelsAsLlmAgentName?: string[] | null;
        } | null;
        thresholdForAutoReject?: number;
        createTaskFromStoryBodyCheckboxEnabled?: boolean;
        queryToAddProjectEnabled?: boolean;
        queryToAddProject?: string | null;
        storyProgressCommentEnabled?: boolean;
        dailySecurityScan?: DailySecurityScanConfig | null;
        developerAgentName?: string | null;
    }) => Promise<{
        project: Project;
        issues: Issue[];
        cacheUsed: boolean;
        targetDateTimes: Date[];
        storyIssues: StoryObjectMap;
        rotationOrder: RotationOrderEntry[] | null;
    } | null>;
    runEachUseCases: (input: Parameters<HandleScheduledEventUseCase["run"]>[0], project: Project, issues: Issue[], cacheUsed: boolean, targetDateTimes: Date[], storyObjectMap: StoryObjectMap, runSlowSweep: boolean, now: Date) => Promise<{
        rotationOrder: RotationOrderEntry[] | null;
    }>;
    runSlowSweepUseCases: (input: Parameters<HandleScheduledEventUseCase["run"]>[0], project: Project, issues: Issue[], cacheUsed: boolean, targetDateTimes: Date[], storyObjectMap: StoryObjectMap) => Promise<void>;
    static createTargetDateTimes: (from: Date, to: Date) => Date[];
    runSpreadsheetOperation: <T>(operation: "read" | "write", spreadsheetUrl: string, org: string, repo: string, manager: Member["name"], action: () => Promise<T>) => Promise<T>;
    findTargetDateAndUpdateLastExecutionDateTime: (spreadsheetUrl: string, now: Date, org: string, repo: string, manager: Member["name"]) => Promise<Date[]>;
    shouldRunSlowSweep: (spreadsheetUrl: string, now: Date, org: string, repo: string, manager: Member["name"]) => Promise<boolean>;
    storyIssues: (input: {
        project: Project;
        issues: Issue[];
    }) => Promise<StoryObjectMap>;
}
//# sourceMappingURL=HandleScheduledEventUseCase.d.ts.map