import { LiveSessionProcessSnapshotProvider } from './adapter-interfaces/LiveSessionProcessSnapshotProvider';
import { InteractiveLiveSessionTranscriptResolver } from './adapter-interfaces/InteractiveLiveSessionTranscriptResolver';
import { OwnerCallStatusProvider } from './adapter-interfaces/OwnerCallStatusProvider';
import { RefusalTailStatusProvider } from './adapter-interfaces/RefusalTailStatusProvider';
import { SessionOutputActivityRepository } from './adapter-interfaces/SessionOutputActivityRepository';
import { SessionSubAgentActivityRepository } from './adapter-interfaces/SessionSubAgentActivityRepository';
import { SilentSessionMessageComposer } from './adapter-interfaces/SilentSessionMessageComposer';
import { SilentSessionNotificationRepository } from './adapter-interfaces/SilentSessionNotificationRepository';
import { SilentSessionCandidateStateRepository } from './adapter-interfaces/SilentSessionCandidateStateRepository';
import { SilentSessionHubTaskStatusCacheRepository } from './adapter-interfaces/SilentSessionHubTaskStatusCacheRepository';
import { Sleeper } from './adapter-interfaces/Sleeper';
import { IssueRepository } from './adapter-interfaces/IssueRepository';
export declare const DEFAULT_MAIN_SILENT_THRESHOLD_SECONDS: number;
export declare const DEFAULT_UNANSWERED_OWNER_CALL_GRACE_SECONDS: number;
export declare const DEFAULT_SUBAGENT_SILENT_THRESHOLD_SECONDS: number;
export declare const DEFAULT_SUBAGENT_RUNNING_THRESHOLD_SECONDS: number;
export declare const DEFAULT_NOTIFICATION_STAGGER_SECONDS = 25;
export declare const DEFAULT_CANDIDATE_DEBOUNCE_RECENCY_WINDOW_SECONDS: number;
export declare const DEFAULT_HUB_TASK_STATUS_CACHE_TTL_SECONDS: number;
export declare const parseHubTaskIssueUrlFromSessionName: (sessionName: string) => string | null;
export declare const isGitHubIssueOrPullRequestSessionName: (sessionName: string) => boolean;
export type HubTaskStatusResolver = Pick<IssueRepository, 'getIssueByUrl'>;
export declare class NotifySilentLiveSessionsUseCase {
    private readonly liveSessionProcessSnapshotProvider;
    private readonly interactiveLiveSessionTranscriptResolver;
    private readonly sessionOutputActivityRepository;
    private readonly subAgentActivityRepository;
    private readonly ownerCallStatusProvider;
    private readonly notificationRepository;
    private readonly candidateStateRepository;
    private readonly messageComposer;
    private readonly sleeper;
    private readonly hubTaskStatusResolver;
    private readonly hubTaskStatusCacheRepository;
    private readonly refusalTailStatusProvider;
    private readonly resolveInteractiveLiveSessions;
    constructor(liveSessionProcessSnapshotProvider: LiveSessionProcessSnapshotProvider, interactiveLiveSessionTranscriptResolver: InteractiveLiveSessionTranscriptResolver, sessionOutputActivityRepository: SessionOutputActivityRepository, subAgentActivityRepository: SessionSubAgentActivityRepository, ownerCallStatusProvider: OwnerCallStatusProvider, notificationRepository: SilentSessionNotificationRepository, candidateStateRepository: SilentSessionCandidateStateRepository, messageComposer: SilentSessionMessageComposer, sleeper: Sleeper, hubTaskStatusResolver?: HubTaskStatusResolver | null, hubTaskStatusCacheRepository?: SilentSessionHubTaskStatusCacheRepository | null, refusalTailStatusProvider?: RefusalTailStatusProvider | null);
    run: (params: {
        mainSilentThresholdSeconds: number;
        unansweredOwnerCallGraceSeconds: number;
        subAgentSilentThresholdSeconds: number;
        subAgentRunningThresholdSeconds: number;
        staggerSeconds: number;
        candidateDebounceRecencyWindowSeconds: number;
        activeHubTaskStatus: string | null;
        hubTaskStatusCacheTtlSeconds: number;
        now: Date;
    }) => Promise<void>;
    private isHubTaskActive;
    private tryResolveAndCacheHubTask;
    private isResolvedStatusActive;
    private collectSnapshots;
    private composeCandidate;
    private reconcileAnnouncedRunningLabels;
}
//# sourceMappingURL=NotifySilentLiveSessionsUseCase.d.ts.map