import { IssueRepository, RelatedPullRequest, IssueComment, PullRequestDetail, PullRequestCommit, PullRequestReviewCommentSide, PullRequestReviewInlineLocation } from '../../../domain/usecases/adapter-interfaces/IssueRepository';
import { Project } from '../../../domain/entities/Project';
import { Issue } from '../../../domain/entities/Issue';
import { StoryObjectMap } from '../../../domain/entities/StoryObjectMap';
import { ApiV3IssueRepository } from './ApiV3IssueRepository';
import { RestIssueRepository } from './RestIssueRepository';
import { GraphqlProjectItemRepository, ProjectItem } from './GraphqlProjectItemRepository';
import { LocalStorageCacheRepository } from '../LocalStorageCacheRepository';
import { BaseGitHubRepository } from '../BaseGitHubRepository';
import { LocalStorageRepository } from '../LocalStorageRepository';
import { Member } from '../../../domain/entities/Member';
import { ProjectRepository } from '../../../domain/usecases/adapter-interfaces/ProjectRepository';
import { DateRepository } from '../../../domain/usecases/adapter-interfaces/DateRepository';
import { Sleep } from './githubRateLimitRetry';
export declare const FULL_ISSUE_FETCH_INTERVAL_MS: number;
export declare const INCREMENTAL_FETCH_SKEW_BUFFER_MS: number;
export declare const REQUIRED_CHECKS_CACHE_TTL_MS: number;
export type CachedProjectIssues = {
    lastFetchedAt: string;
    lastFullFetchAt: string;
    project: Project;
    issues: Issue[];
};
export declare class ApiV3CheerioRestIssueRepository extends BaseGitHubRepository implements IssueRepository {
    readonly apiV3IssueRepository: Pick<ApiV3IssueRepository, 'searchIssue'>;
    readonly restIssueRepository: Pick<RestIssueRepository, 'createNewIssue' | 'updateIssue' | 'createComment' | 'getIssue' | 'updateLabels' | 'removeLabel' | 'updateAssigneeList'>;
    readonly graphqlProjectItemRepository: Pick<GraphqlProjectItemRepository, 'fetchProjectItems' | 'fetchProjectItemsLight' | 'fetchProjectItemsByIds' | 'fetchProjectItemByUrl' | 'updateProjectField' | 'clearProjectField' | 'updateProjectTextField' | 'addIssueToProject'>;
    readonly localStorageCacheRepository: Pick<LocalStorageCacheRepository, 'getSingle' | 'setSingle'>;
    readonly projectRepository: Pick<ProjectRepository, 'getProject'>;
    readonly dateRepository: DateRepository;
    readonly localStorageRepository: LocalStorageRepository;
    readonly ghToken: string;
    readonly sleep: Sleep;
    constructor(apiV3IssueRepository: Pick<ApiV3IssueRepository, 'searchIssue'>, restIssueRepository: Pick<RestIssueRepository, 'createNewIssue' | 'updateIssue' | 'createComment' | 'getIssue' | 'updateLabels' | 'removeLabel' | 'updateAssigneeList'>, graphqlProjectItemRepository: Pick<GraphqlProjectItemRepository, 'fetchProjectItems' | 'fetchProjectItemsLight' | 'fetchProjectItemsByIds' | 'fetchProjectItemByUrl' | 'updateProjectField' | 'clearProjectField' | 'updateProjectTextField' | 'addIssueToProject'>, localStorageCacheRepository: Pick<LocalStorageCacheRepository, 'getSingle' | 'setSingle'>, projectRepository: Pick<ProjectRepository, 'getProject'>, dateRepository: DateRepository, localStorageRepository: LocalStorageRepository, ghToken?: string, sleep?: Sleep);
    private readonly getAllIssuesRefreshMemo;
    private fetchWithRateLimitRetry;
    updateStatus: (project: Project, issue: Issue, statusId: string) => Promise<void>;
    convertProjectItemToIssue: (item: ProjectItem) => Issue;
    private restoreIssuesFromCache;
    private readCachedProjectIssues;
    getCachedProject: (projectId: Project["id"]) => Promise<Project | null>;
    private toDateString;
    getAllIssues: (projectId: Project["id"]) => Promise<{
        issues: Issue[];
        project: Project;
        cacheUsed: boolean;
    }>;
    private refreshAllIssues;
    createNewIssue: (org: string, repo: string, title: string, body: string, assignees: string[], labels: string[]) => Promise<number>;
    searchIssue: (query: {
        owner: string;
        repositoryName: string;
        type?: "issue" | "pr";
        state?: "open" | "closed" | "all";
        title?: string;
        createdFrom?: string;
        assignee?: string;
    }) => Promise<{
        url: string;
        title: string;
        number: string;
    }[]>;
    updateIssue: (issue: Issue) => Promise<void>;
    getIssueByUrl: (url: string) => Promise<Issue | null>;
    addIssueToProject: (project: Project, issueUrl: string) => Promise<void>;
    setDependedIssueUrl: (prUrl: string, project: Project, issueUrl: string) => Promise<void>;
    updateNextActionDate: (issueUrl: string, project: Project, date: Date, projectItemId?: string) => Promise<void>;
    updateNextActionHour: (project: Project & {
        nextActionHour: NonNullable<Project["nextActionHour"]>;
    }, issue: Issue, hour: number) => Promise<void>;
    updateStory: (project: Project & {
        story: NonNullable<Project["story"]>;
    }, issue: Issue, storyOptionId: string) => Promise<void>;
    clearProjectField: (project: Project, fieldId: string, issue: Issue) => Promise<void>;
    createComment: (issue: Issue, comment: string) => Promise<void>;
    updateProjectTextField: (project: Project, fieldId: string, issue: Issue, text: string) => Promise<void>;
    updateLabels: (issue: Issue, labels: Issue["labels"]) => Promise<void>;
    removeLabel: (issue: Issue, label: string) => Promise<void>;
    updateAssigneeList: (issue: Issue, assigneeList: Member["name"][]) => Promise<void>;
    get: (_issueUrl: string, _project: Project) => Promise<Issue | null>;
    update: (issue: Issue, _project: Project) => Promise<void>;
    private parseIssueUrl;
    private computePrStatus;
    private readonly requiredCheckNamesCache;
    private getRequiredCheckNames;
    private getCommitCiContexts;
    private fetchSlimPullRequest;
    private buildRelatedPullRequestFromSlim;
    private resolveMergeabilityWithRetry;
    findRelatedOpenPRs: (issueUrl: string) => Promise<RelatedPullRequest[]>;
    getAllOpened: (project: Project) => Promise<Issue[]>;
    getStoryObjectMap: (project: Project) => Promise<StoryObjectMap>;
    getOpenPullRequest: (prUrl: string) => Promise<RelatedPullRequest | null>;
    closePullRequest: (prUrl: string) => Promise<void>;
    closeIssueByUrl: (issueUrl: string, stateReason: "completed" | "not_planned") => Promise<void>;
    getPullRequestChangedFilePaths: (prUrl: string) => Promise<string[]>;
    approvePullRequest: (prUrl: string) => Promise<void>;
    requestChangesWithInlineComment: (prUrl: string, changedFilePath: string | null, commentBody: string, inlineCommentLocation?: PullRequestReviewInlineLocation | null) => Promise<void>;
    private fetchPullRequestHeadSha;
    createPullRequestReviewComment: (prUrl: string, path: string, line: number, side: PullRequestReviewCommentSide, commentBody: string) => Promise<void>;
    private readGitHubErrorReason;
    private formatGitHubErrorWithStatus;
    deletePullRequestBranch: (prUrl: string, branchName: string) => Promise<void>;
    createCommentByUrl: (issueOrPrUrl: string, commentBody: string) => Promise<void>;
    getIssueOrPullRequestBody: (url: string) => Promise<string>;
    getIssueOrPullRequestComments: (url: string) => Promise<IssueComment[]>;
    getPullRequestDetail: (prUrl: string) => Promise<PullRequestDetail | null>;
    private fetchPullRequestFiles;
    getPullRequestCommits: (prUrl: string) => Promise<PullRequestCommit[]>;
    getIssueOrPullRequestState: (url: string) => Promise<{
        state: string;
        merged: boolean;
        isPullRequest: boolean;
    }>;
    getPullRequestSummary: (prUrl: string) => Promise<{
        title: string;
        body: string;
        additions: number;
        deletions: number;
        changedFiles: number;
    } | null>;
}
//# sourceMappingURL=ApiV3CheerioRestIssueRepository.d.ts.map