export type ClaudeMessageResponse = {
  id: string;
  observedAt: Date;
  tokenName: string;
  externalClaudeMessageId: string | null;
  externalClaudeRequestId: string | null;
  httpStatus: number;
  model: string | null;
  role: string | null;
  stopReason: string | null;
  stopSequence: string | null;
  inputTokens: number | null;
  outputTokens: number | null;
  cacheCreationInputTokens: number | null;
  cacheReadInputTokens: number | null;
  ephemeral5mInputTokens: number | null;
  ephemeral1hInputTokens: number | null;
  serviceTier: string | null;
  inferenceGeo: string | null;
  errorType: string | null;
  errorMessage: string | null;
  anthropicRatelimitUnifiedStatus: string | null;
  anthropicRatelimitUnified5hStatus: string | null;
  anthropicRatelimitUnified5hUtilization: number | null;
  anthropicRatelimitUnified5hReset: number | null;
  anthropicRatelimitUnified7dStatus: string | null;
  anthropicRatelimitUnified7dUtilization: number | null;
  anthropicRatelimitUnified7dReset: number | null;
  retryAfter: number | null;
  anthropicOrganizationId: string | null;
};
